TheArt/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheArt.Models
{
    public class Artist
    {
        public Artist()
        {
            this.Movements = new HashSet<ArtistMovement>();
            this.Pieces = new HashSet<Piece>();
        }
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfDeath { get; set; }
        public ICollection<Piece> Pieces { get; set; }
        public ICollection<ArtistMovement> Movements { get; set;} 
    }
}

TheArt/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using TheArt.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheArt.Controllers
{
  public class ArtistsController : Controller
  {
    private readonly TheArtContext _db;

    public ArtistsController(TheArtContext db) //checked
    {
      _db = db;
    }

    public ActionResult Index() //unsure
    {
      List<Artist> model = _db.Artists.ToList(); //create list out of database table called artists
      return View(model);
    }

    public ActionResult Create() //good
    {
      ViewBag.MovementId = new SelectList(_db.Movements, "MovementId", "MovementName");
      ViewBag.Piece = new SelectList(_db.Pieces, "PieceId", "PieceName");
      return View();
    }

    [HttpPost]

    public ActionResult Create(Artist artist, int MovementId) //good
    {
      _db.Artists.Add(artist); // if conditional statement below is not true then just add artist object to list of artists
      if(MovementId != 0)
      {
        _db.ArtistMovement.Add(new ArtistMovement() {MovementId = MovementId, ArtistId = artist.ArtistId}); // we did artist.ArtistId because we passed the artist object as an argument to create so we have to go inside and grab the ArtistId
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id) //good
    {
      var thisArtist = _db.Artists
        .Include(artist => artist.Pieces)
        .Include(artist => artist.Movements)
        .ThenInclude(join => join.Movement)
        .FirstOrDefault(artist => artist.ArtistId == id);
      return View(thisArtist);
    }


    public ActionResult Edit(int id) //good
    {
      var thisArtist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      ViewBag.MovementId = new SelectList(_db.Movements, "MovementId", "MovementName");
      ViewBag.PieceId = new SelectList(_db.Pieces, "PieceId", "PieceName");
      return View(thisArtist);
    }
  
    [HttpPost]
    public ActionResult Edit(Artist artist, int MovementId) //good
    {
      if (MovementId != 0)
      {
        _db.ArtistMovement.Add(new ArtistMovement() { MovementId = MovementId, ArtistId = artist.ArtistId });
      }
      _db.Entry(artist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id) //good
    {
      var thisArtist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      return View(thisArtist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id) //good
    {
      var thisArtist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      _db.Artists.Remove(thisArtist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMovement(int joinId) // good
    {
      var joinEntry = _db.ArtistMovement.FirstOrDefault(entry => entry.ArtistMovementId == joinId); // seperates the join table so you can remove a movement
      _db.ArtistMovement.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    
    public ActionResult AddMovement(int id) //good
    {
      var thisArtist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      ViewBag.MovementId = new SelectList(_db.Movements, "MovementId", "MovementName");
      return View(thisArtist);
    }

    [HttpPost]
    public ActionResult AddMovement(Artist artist, int MovementId) //good
    {
      if (MovementId != 0)
      {
        _db.ArtistMovement.Add(new ArtistMovement() { MovementId = MovementId, ArtistId = artist.ArtistId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TheArt/Controllers/MovementsController.cs
using Microsoft.AspNetCore.Mvc;
using TheArt.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheArt.Controllers
{
  public class MovementsController : Controller
  {
    private readonly TheArtContext _db;

    public MovementsController(TheArtContext db) //checked
    {
      _db = db;
    }

    public ActionResult Index() //checked
    {
      List<Movement> model = _db.Movements.ToList();
      return View(model);
    }

    public ActionResult Create() //checked
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Movement movement) //checked
    {
      _db.Movements.Add(movement);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id) //checked
    {
      var thisMovement = _db.Movements
          .Include(movement => movement.Artists)
          .ThenInclude(join => join.Artist)
          .FirstOrDefault(movement => movement.MovementId == id);
      return View(thisMovement);
    }

    public ActionResult Edit(int id) //checked
    {
      var thisMovement = _db.Movements.FirstOrDefault(movements => movements.MovementId == id);
      ViewBag.ArtistId = new SelectList(_db.Artists, "ArtistId", "ArtistName");
      return View(thisMovement);
    }

    [HttpPost]
    public ActionResult Edit(Movement movement, int ArtistId) //checked
    {
      if(ArtistId != 0)
      {
        _db.ArtistMovement.Add(new ArtistMovement() {ArtistId = ArtistId, MovementId = movement.MovementId});
      }
      _db.Entry(movement).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id) //checked
    {
      var thisMovement = _db.Movements.FirstOrDefault(movement => movement.MovementId == id);
      return View(thisMovement);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id) //checkedd
    {
      var thisMovement = _db.Movements.FirstOrDefault(movement => movement.MovementId == id);
      _db.Movements.Remove(thisMovement);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TheArt/Views/Artists/AddMovement.cshtml
@{
  Layout = "_Layout";
}

@model TheArt.Models.Artist

<h1>Add a Movent</h1>

<h4>Add a Movement to this artist: @Html.DisplayFor(model => model.ArtistName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ArtistId)

    @Html.Label("Select movement")
    @Html.DropDownList("MovementId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to artists", "Index")</p>

TheArt/Views/Artists/Create.cshtml
@{
  Layout = "_Layout";
}

@model TheArt.Models.Artist

<h1>New Artist</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.ArtistName)
  @Html.TextBoxFor(model => model.ArtistName)
  <input type="submit" value="add" />
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("All artists", "Index")</p>

TheArt/Views/Artists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TheArt.Models.Artist

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.ArtistName)?</h2>

@Html.DisplayNameFor(model => model.ArtistName): @Html.DisplayFor(model => model.ArtistName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("All artists", "Index")
@Html.ActionLink("Home", "Index", "Home")

TheArt/Views/Artists/Details.cshtml
@{
  Layout = "_Layout";
}

@using TheArt.Models;
@model TheArt.Models.Artist

<h1>Artist Details</h1>
<hr />
<h2>@Html.DisplayFor(model => model.ArtistName)</h2>

@if(@Model.Pieces.Count() == 0)
{
  <p>this guy is kind of a lazy dude. he hasn't made anything.</p>
}
else
{
  <h4>Pieces:</h4>
  <ul>
    @foreach(Piece piece in Model.Pieces)
    {
      <li>@piece.PieceName</li>
    }
  </ul>
}

@if(@Model.Movements.Count() == 0)
{
  <p>this guy isn't a part of a movement</p>
}
else
{
  <h4>Movements: </h4>
  <ul>
    @foreach(var join in Model.Movements)
    {
      <li>@Html.ActionLink($"{join.Movement.MovementName}", "Details", "Movements", new { id = @join.Movement.MovementId})</li>
      @using (Html.BeginForm("DeleteMovement", "Artists"))
      {
        @Html.Hidden("joinId", @join.ArtistMovementId)
        @Html.Hidden("artistId", Model.ArtistId);
        <input type="submit" value="Remove This movement" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Edit Artist", "Edit", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Delete Artist", "Delete", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheArt/Views/Artists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TheArt.Models.Artist

<h2>Edit @Html.DisplayFor(model => model.ArtistName)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ArtistId)

  @Html.LabelFor(model => model.ArtistName)
  @Html.TextBoxFor(model => model.ArtistName)

  @Html.Label("Add Movement:") 
  @Html.DropDownList("MovementId")

  @Html.Label("Add Piece:")
  @Html.DropDownList("PieceId")

  <input type="submit" value="Update" />
}

<p>@Html.ActionLink("Artist Index", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheArt/Views/Artists/Index.cshtml
@{
  Layout = "_Layout";
}

@using TheArt.Models;
@model List<TheArt.Models.Artist>;


<h1>Artists</h1>

@if(@Model.Count() == 0)
{
  <h3>there are no artists</h3>
}
else
{
  <ul>
    @foreach(Artist artist in Model)
    {
      <li>@Html.ActionLink($"{artist.ArtistName}", "Details", new { id = artist.ArtistId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add an artist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>